font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.5

disable_ligatures never
adjust_line_height 2
adjust_column_width 0

cursor_shape block
cursor_blink_interval 0
cursor #f2f2f2
cursor_text_color #111111

scrollback_lines 10000
wheel_scroll_multiplier 5.0

enable_audio_bell no
visual_bell_duration 0
window_alert_on_bell no

remember_window_size yes
initial_window_width 100c
initial_window_height 28c
window_padding_width 14

hide_window_decorations yes
background_opacity 0.94
background_blur 16

active_border_color   #e8e8e8
inactive_border_color #303030

selection_foreground #111111
selection_background #cfcfcf

foreground #e8e8e8
background #111111
color0  #1a1a1a
color1  #ff7a7a
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #c0caf5
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #ffffff

tab_bar_style hidden
tab_separator " "
tab_title_template "{title}"

shell_integration enabled
copy_on_select clipboard
