[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding="0"

Font="Open Sans"
FontSize="13"

KeyboardSize="0.4"
RoundCorners="20"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/minimal-dark-login.jpg"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.15"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#e8e8e8"
DateTextColor="#e8e8e8"
TimeTextColor="#e8e8e8"

FormBackgroundColor="#111111"
BackgroundColor="#111111"
DimBackgroundColor="#111111"

LoginFieldBackgroundColor="#1a1a1a"
PasswordFieldBackgroundColor="#1a1a1a"
LoginFieldTextColor="#e8e8e8"
PasswordFieldTextColor="#e8e8e8"
UserIconColor="#e8e8e8"
PasswordIconColor="#e8e8e8"

PlaceholderTextColor="#6b7280"
WarningColor="#f7768e"

LoginButtonTextColor="#111111"
LoginButtonBackgroundColor="#7aa2f7"
SystemButtonsIconsColor="#e8e8e8"
SessionButtonTextColor="#e8e8e8"
VirtualKeyboardButtonTextColor="#e8e8e8"

DropdownTextColor="#e8e8e8"
DropdownSelectedBackgroundColor="#202020"
DropdownBackgroundColor="#1a1a1a"

HighlightTextColor="#111111"
HighlightBackgroundColor="#7dcfff"
HighlightBorderColor="#303030"

HoverUserIconColor="#7dcfff"
HoverPasswordIconColor="#7dcfff"
HoverSystemButtonsIconsColor="#7dcfff"
HoverSessionButtonTextColor="#7dcfff"
HoverVirtualKeyboardButtonTextColor="#7dcfff"

#################### Form ####################

PartialBlur="true"
FullBlur="false"
BlurMax="48"
Blur="1.0"

HaveFormBackground="false"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
